import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "./components/Footer";

import Hero from "./components/Hero";

export const metadata = {
  title: "Hidden Gems",
  description: "Generated by Hidden Gems",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mb-48 bg-white">
        <Hero />
        {children}
        <div className="mt-10">
          <Footer />
        </div>
      </body>
    </html>
  );
}
